-- Add entry analytics for Beauty лов and allow the current admin UI to read it.

alter table public.catch_game_results
  add column if not exists session_id text;

create index if not exists catch_game_results_session_id_idx
  on public.catch_game_results (session_id, created_at desc);

drop policy if exists "CatchCare analytics can be read from app" on public.catch_game_results;

-- The current admin identity is client-side. This follows the existing admin
-- model; move analytics reads behind verified Telegram initData before public use.
create policy "CatchCare analytics can be read from app"
on public.catch_game_results
for select
to anon, authenticated
using (true);

create table if not exists public.catch_game_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  phone text not null,
  last_name text not null default '',
  tg_user_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists catch_game_sessions_created_at_idx
  on public.catch_game_sessions (created_at desc);

create index if not exists catch_game_sessions_phone_idx
  on public.catch_game_sessions (phone, created_at desc);

alter table public.catch_game_sessions enable row level security;

drop policy if exists "Beauty game sessions can be created from app" on public.catch_game_sessions;
drop policy if exists "Beauty game sessions can be read from app" on public.catch_game_sessions;

create policy "Beauty game sessions can be created from app"
on public.catch_game_sessions
for insert
to anon, authenticated
with check (char_length(session_id) between 8 and 120);

create policy "Beauty game sessions can be read from app"
on public.catch_game_sessions
for select
to anon, authenticated
using (true);
